version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_network
  mongo:
    container_name: mongo-admin-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - rabbitmq_network
  admin-container:
    build:
      dockerfile: Dockerfile
      context: "./micro-admin-backend"
      target: development
    volumes:
      - "./micro-admin-backend:/app"
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    depends_on: 
      - mongo
      - rabbitmq
      # debugging port
    networks:
      - rabbitmq_network
  api-container:
    build:
      dockerfile: Dockerfile
      context: "./api-gateway"
      target: development
    volumes:
      - "./api-gateway:/app"
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    depends_on: 
      - mongo
      - rabbitmq
      # debugging port
    networks:
      - rabbitmq_network
    ports:
      - "8888:8888"
networks:
  rabbitmq_network:
    driver: bridge